spring.application.name=barberweb

#Database MySQL config
spring.datasource.url=jdbc:mysql:https://localhost:3306/mainBD
spring.datasource.username=${DB_PASSWORD}
spring.datasource.password=${DB_USER}
spring.jpa.hibernate.dll-auto=update

#MySQL Dialect (Opcional)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Server Config
server.port=5453



