spring.application.name=barberweb

#Database MySQL config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=true

spring.flyaway.enabled=false

#MySQL Dialect (Opcional)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Server Config
server.port=${SERVER_PORT}


